### ISSUE TITLE
Upstream doesn't work on High Sierra 10.13.6

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#382]
High Sierra is still supported until November 30, 2020.

```
➜  ~  /Applications/radicle-upstream.app/Contents/MacOS/radicle-upstream
objc[94843]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8d4a5cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11fe9fcd8). One of the two will be used. Which one is undefined.
Error: Command failed: /Applications/radicle-upstream.app/Contents/Resources/proxy --registry=emulator
 INFO  proxy > Starting API
 INFO  warp::server > listening on http://127.0.0.1:8080
 INFO  proxy::http  > "GET /v1/session HTTP/1.1" 200 1.11392ms
 INFO  proxy::http  > "GET /v1/projects HTTP/1.1" 200 1.143221ms
 INFO  proxy::http  > "POST /v1/transactions HTTP/1.1" 200 2.309396ms
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/radicle-upstream.app/Contents/Resources/proxy (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/radicle-upstream.app/Contents/Resources/proxy (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib


    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:658:12) {
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd: '/Applications/radicle-upstream.app/Contents/Resources/proxy --registry=emulator'
}
```

@abbey-titcomb can reproduce this on her laptop.

**Comment by rudolfs** [comment]
Maybe we should have a screen-of-death for situations where the proxy can't start up? \cc @brandonhaslegs @juliendonck @cloudhead

**Comment by rudolfs** [comment]
Closing this as @abbey-titcomb upgraded to Catalina and High Sierra is being EOLd soon anyway.

**Comment by rudolfs** [comment]
During our onboarding session John couldn't onboard because he was on `10.13.6`:

```
INFO coco::git_helper > Copied git remote helper to: "/Users/levelk/.radicle/bin/git-remote-rad"
INFO api::process > starting API
ERROR api::http::error > Rejection(NoSession)
INFO proxy::http > "GET /v1/session HTTP/1.1" 404 251.035µs
INFO proxy::http > "POST /v1/keystore HTTP/1.1" 204 110.199827ms
INFO librad::net::protocol > Protocol::run; local.id=hydcm5hk86bc8oujnq7duz1y38dce9bo7aiqyf1rsmhu1nw1x5o6u4 local.addr=0.0.0.0:49982
INFO api::process > starting API
INFO api::process > starting peer
INFO librad::net::protocol > Listening
INFO librad::net::protocol > Establishing connection remote.id=hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
Referenced from: /Applications/Radicle Upstream.app/Contents/Resources/proxy (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
Referenced from: /Applications/Radicle Upstream.app/Contents/Resources/proxy (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by juliendonck** [comment]
It's supported for another 5 days...

**Comment by cloudhead** [comment]
Can we decide how many releases back we want to support?

**Comment by rudolfs** [comment]
> Can we decide how many releases back we want to support?

Ideally we should support whatever the vendor is still supporting.

**Comment by xla** [comment]
Will be not supported after Monday, so #wontfix.
